# Generated by Django 4.2.4 on 2023-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=15)),
                ('highest_education', models.CharField(max_length=40)),
                ('institute', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=20)),
                ('work_exp', models.CharField(max_length=100)),
                ('inscanada', models.CharField(max_length=100)),
                ('POS', models.CharField(max_length=50)),
                ('feepaid', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('completed_gic', models.CharField(max_length=10)),
                ('gicamount', models.IntegerField()),
                ('read', models.IntegerField()),
                ('write', models.IntegerField()),
                ('speak', models.IntegerField()),
                ('listen', models.IntegerField()),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
